### ISSUE TITLE
Ultimate Lab 1

### ISSUE THREAD

**Issue by kaewtar** [kaewtar/objectOP#3]

**Comment by kaewtar** [comment]
import java.util.Scanner;

public class SortingNumber {

    public static void AscendingOrderByUsingBubble(int[] my){

            int value;
            for (int k = 0; k < my.length; k++) {
                for (int l = k + 1; l < my.length; l++) {
                    if (my[k] > my[l]) {
                        value = my[k];
                        my[k] = my[l];
                        my[l] = value;
                    }
                }
            }
        System.out.println("This is bubble sort >>>");
    }

    public static void AscendingOrderByUsingInsertion(int[] my){
        int n = my.length;
        for (int i = 1; i < n; ++i) {
            int key = my[i];
            int j = i - 1;

            while (j >= 0 && my[j] > key) {
                my[j + 1] = my[j];
                j = j - 1;
            }
        my[j + 1] = key;
        }
        System.out.println("This is insertion sort >>>");
    }



    public static void Print(int [] my){
        for (int k : my) System.out.println(k);
    }




    public static void main(String[] args){
        Scanner s = new Scanner(System.in);
        System.out.println("Enter your number: ");
        int number = s.nextInt();

        if(number < 0) System.out.println("error");
        else {
            int[] my = new int[number];
            for (int i = 0; i < my.length; i++) {
                System.out.println("Enter your number value: ");
                my[i] = s.nextInt();
            }

            AscendingOrderByUsingBubble(my);
            Print(my);
            AscendingOrderByUsingInsertion(my);
            Print(my);
        }
    }

}

**Comment by kanonlas** [comment]
insertion = เอาตัวปจบเทียบก่อนหน้า ถ้าตัวปจบมีค่ามากกว่าตัวก่อนหน้าให้อยู่ที่เดิม เเต่ถ้ามีค่าน้อยกว่าให้เทียบตัวก่อนหน้าต่อวนลูปไป
selection =  วนลูปหาตัวที่น้อยที่สุดมาเป็น min เเล้วนำไปใส่ใน array[0] วนลูปตั้งเเต่ array 1 ใหม่ตั้งตัวเเรก min เทียบหา min ใน array ตัวต่อไปมาใส่ใน array[1] วนไปเรื่อยๆ จนครบ
bubble sort = จับคู่ เเล้วเทียบค่า น้อยกว่า swap check 2 ลูปซ้อนไปเรื่อยๆ
